### ISSUE TITLE
Ancient Sword Of Runes, was taken down

### ISSUE THREAD

**Issue by LordDaiki** [Millionsfrost/N.Y.A-NSFW-Modlist-Skyrim#9]
Ancient Sword Of Runes-121911-1-2-1718541509.rar 
Cannot be downloaded via Wabbajack anymore.

Need help for a replacement to install it manually.

Here is the problem and link
https://www.nexusmods.com/skyrimspecialedition/mods/121911?tab=files&file_id=511703
![Screenshot 2024-06-26 182332](https://github.com/Millionsfrost/N.Y.A-NSFW-Modlist-Skyrim/assets/98053731/f5a8738e-fa6f-4016-b89b-47fd4a5b85da)

**Comment by Millionsfrost** [comment]
We know , we already posted an Announcment. Will be fixed in 1-2 Days.

**Comment by LordDaiki** [comment]
ok Thanks and sorry
